python = {
    "nodes": [
        {
            "preceding_lines": ["# test taxonomy"],
            "src_position": 1,
            "id": "__header__",
            "labels": {"p_test_testbranch", "t_test", "b_testbranch", "TEXT"},
        },
        {
            "is_before": "__header__",
            "preceding_lines": [],
            "src_position": 3,
            "tags_fr": ["aux", "au", "de", "le", "du", "la", "a", "et"],
            "id": "stopwords:0",
            "labels": {"p_test_testbranch", "t_test", "b_testbranch", "STOPWORDS"},
        },
        {
            "tags_en": ["passion fruit", "passionfruit"],
            "is_before": "stopwords:0",
            "preceding_lines": [],
            "src_position": 5,
            "id": "synonyms:0",
            "tags_ids_en": ["passion-fruit", "passionfruit"],
            "labels": {"SYNONYMS", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["fruit-passion", "fruits-passion", "maracuja", "passion"],
            "is_before": "synonyms:0",
            "preceding_lines": [""],
            "src_position": 7,
            "tags_fr": ["fruit de la passion", "fruits de la passion", "maracuja", "passion"],
            "id": "synonyms:1",
            "labels": {"SYNONYMS", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts", "yoghourts", "yogourts"],
            "prop_color_en": " white",
            "preceding_lines": [],
            "src_position": 9,
            "tags_fr": ["yaourts", "yoghourts", "yogourts"],
            "tags_ids_en": ["yogurts", "yoghurts"],
            "tags_ids_nl": ["yoghurts"],
            "main_language": "en",
            "tags_en": ["yogurts", "yoghurts"],
            "is_before": "synonyms:1",
            "prop_flavour_en": " undef",
            "prop_description_en": " a yogurts of whatever type",
            "prop_description_fr": " un yaourt de n'importe quel type",
            "id": "en:yogurts",
            "tags_nl": ["yoghurts"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts-banane"],
            "prop_color_en": " yellow",
            "preceding_lines": [],
            "src_position": 17,
            "tags_fr": ["yaourts à la banane"],
            "tags_ids_en": ["banana-yogurts"],
            "tags_ids_nl": ["bananenyoghurt"],
            "main_language": "en",
            "tags_en": ["banana yogurts"],
            "is_before": "en:yogurts",
            "prop_flavour_en": " banana",
            "prop_description_en": " a banana yogurt",
            "prop_description_fr": " un yaourt à la banane",
            "id": "en:banana-yogurts",
            "tags_nl": ["bananenyoghurt"],
            "parents": ["en:yogurts"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts-fruit-passion"],
            "prop_color_en": " undef",
            "preceding_lines": [],
            "src_position": 26,
            "tags_fr": ["yaourts au fruit de la passion"],
            "tags_ids_en": ["passion-fruit-yogurts"],
            "tags_ids_nl": ["yoghurts-met-passievrucht"],
            "main_language": "en",
            "tags_en": ["Passion fruit yogurts"],
            "is_before": "en:banana-yogurts",
            "prop_flavour_en": " passion fruit",
            "id": "en:passion-fruit-yogurts",
            "tags_nl": ["yoghurts met passievrucht"],
            "parents": ["en:yogurts"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts-alleges"],
            "main_language": "fr",
            "is_before": "en:passion-fruit-yogurts",
            "preceding_lines": [],
            "src_position": 33,
            "tags_fr": ["yaourts allégés"],
            "id": "fr:yaourts-alleges",
            "parents": ["en:yogurts"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts-citron"],
            "prop_color_en": " yellow",
            "preceding_lines": [],
            "src_position": 36,
            "tags_fr": ["yaourts au citron"],
            "tags_ids_en": ["lemon-yogurts"],
            "main_language": "en",
            "tags_ids_nl": ["yoghurts-met-citroen"],
            "tags_en": ["lemon yogurts"],
            "is_before": "fr:yaourts-alleges",
            "prop_flavour_en": " lemon",
            "prop_description_en": " a yogurts with lemon inside",
            "prop_description_fr": " un yaourt avec du citron",
            "id": "en:lemon-yogurts",
            "tags_nl": ["yoghurts met citroen"],
            "parents": ["fr:yoghourts"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts-fruit-passion-alleges"],
            "main_language": "fr",
            "tags_ids_nl": ["magere-yoghurts-met-passievrucht"],
            "is_before": "en:lemon-yogurts",
            "preceding_lines": [],
            "src_position": 45,
            "tags_fr": ["yaourts au fruit de la passion allégés"],
            "id": "fr:yaourts-fruit-passion-alleges",
            "tags_nl": ["magere yoghurts met passievrucht"],
            "parents": ["fr:yaourts-fruit-passion", "fr:yaourts-alleges"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts-citron-alleges"],
            "main_language": "fr",
            "tags_ids_nl": ["magere-citroenyoghurt"],
            "is_before": "fr:yaourts-fruit-passion-alleges",
            "preceding_lines": [""],
            "src_position": 51,
            "tags_fr": ["yaourts au citron allégés"],
            "prop_description_en": " for light yogurts with lemon",
            "id": "fr:yaourts-citron-alleges",
            "tags_nl": ["magere citroenyoghurt"],
            "parents": ["fr:yaourts-citron", "fr:yaourts-alleges"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["yaourts-myrtille"],
            "main_language": "fr",
            "tags_ids_nl": ["bosbessenyoghurt"],
            "is_before": "fr:yaourts-citron-alleges",
            "preceding_lines": [],
            "src_position": 57,
            "prop_flavour_en": " blueberry",
            "tags_fr": ["yaourts à la myrtille"],
            "id": "fr:yaourts-myrtille",
            "prop_flavour_fr": " myrtille",
            "tags_nl": ["bosbessenyoghurt"],
            "parents": ["fr:yaourt"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "prop_vegan_en": "no",
            "tags_en": ["meat"],
            "is_before": "fr:yaourts-myrtille",
            "preceding_lines": [],
            "src_position": 63,
            "id": "en:meat",
            "tags_ids_en": ["meat"],
            "prop_carbon_footprint_fr_foodges_value_fr": "10",
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "tags_en": ["beef"],
            "is_before": "en:meat",
            "preceding_lines": [],
            "src_position": 67,
            "id": "en:beef",
            "tags_ids_en": ["beef"],
            "parents": ["en:meat"],
            "prop_carbon_footprint_fr_foodges_value_fr": "15",
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "tags_en": ["roast-beef"],
            "is_before": "en:beef",
            "preceding_lines": [],
            "src_position": 71,
            "id": "en:roast-beef",
            "tags_ids_en": ["roast-beef"],
            "parents": ["en:beef"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "prop_vegan_en": "yes",
            "tags_en": ["fake-meat"],
            "is_before": "en:roast-beef",
            "preceding_lines": ["# undef will stop parents from transmitting a value"],
            "src_position": 74,
            "id": "en:fake-meat",
            "tags_ids_en": ["fake-meat"],
            "parents": ["en:meat"],
            "prop_carbon_footprint_fr_foodges_value_fr": "undef",
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "tags_en": ["fake-stuff"],
            "preceding_lines": [],
            "is_before": "en:fake-meat",
            "src_position": 80,
            "id": "en:fake-stuff",
            "tags_ids_en": ["fake-stuff"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "tags_en": ["fake-duck-meat"],
            "is_before": "en:fake-stuff",
            "preceding_lines": [],
            "src_position": 82,
            "id": "en:fake-duck-meat",
            "tags_ids_en": ["fake-duck-meat"],
            "parents": ["en:fake-stuff", "en:fake-meat"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "prop_vegan_en": "yes",
            "main_language": "en",
            "tags_en": ["vegetable"],
            "is_before": "en:fake-duck-meat",
            "preceding_lines": [],
            "src_position": 86,
            "id": "en:vegetable",
            "tags_ids_en": ["vegetable"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "prop_vegan_en": "maybe",
            "tags_ids_xx": [
                "something-that-means-soup-in-every-language",
                "something-else-that-means-soup-in-every-language",
            ],
            "tags_en": ["soup"],
            "is_before": "en:vegetable",
            "preceding_lines": [
                "# the soup yogourt synonym is used to test suggestions matching xx: synonyms"
            ],
            "src_position": 90,
            "id": "en:soup",
            "tags_xx": [
                "something that means soup in every language",
                "something else that means soup in every language",
            ],
            "tags_ids_en": ["soup"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "prop_vegan_en": "yes",
            "tags_en": ["vegan-soup"],
            "is_before": "en:soup",
            "preceding_lines": [],
            "src_position": 94,
            "id": "en:vegan-soup",
            "tags_ids_en": ["vegan-soup"],
            "parents": ["en:soup"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "prop_vegan_en": "no",
            "tags_en": ["fish-soup"],
            "is_before": "en:vegan-soup",
            "preceding_lines": [],
            "src_position": 98,
            "id": "en:fish-soup",
            "tags_ids_en": ["fish-soup"],
            "parents": ["en:soup"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "de",
            "preceding_lines": [],
            "is_before": "en:fish-soup",
            "tags_ids_de": ["spätzle"],
            "src_position": 102,
            "id": "de:spätzle",
            "tags_de": ["Spätzle"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "tags_en": ["Kale"],
            "is_before": "de:spätzle",
            "tags_ids_de": ["grünkohl"],
            "preceding_lines": [],
            "src_position": 104,
            "id": "en:kale",
            "tags_de": ["Grünkohl"],
            "tags_ids_en": ["kale"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["kefir-2-5"],
            "preceding_lines": [],
            "src_position": 107,
            "tags_fr": ["Kéfir 2‚5 %"],
            "tags_ids_ru": ["кефир-2.5"],
            "tags_ids_en": ["kefir-2.5"],
            "main_language": "en",
            "tags_ru": ["Кефир 2.5 %", "Кефир 2.5%"],
            "tags_en": ["Kefir 2.5 %"],
            "is_before": "en:kale",
            "tags_ids_de": ["kefir-2.5"],
            "id": "en:kefir-2.5",
            "tags_de": ["Kefir 2.5 %"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["french-entry"],
            "main_language": "fr",
            "is_before": "en:kefir-2.5",
            "tags_ids_de": ["special-value-for-german"],
            "preceding_lines": [],
            "src_position": 112,
            "tags_fr": ["French entry"],
            "id": "fr:french-entry",
            "tags_de": ["Special value for German"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "tags_ids_fr": ["french-entry-with-default-value"],
            "main_language": "fr",
            "tags_ids_xx": ["french-entry-with-default-value"],
            "is_before": "fr:french-entry",
            "tags_ids_de": ["special-value-for-german-2"],
            "preceding_lines": [],
            "src_position": 115,
            "tags_fr": ["French entry with default value"],
            "id": "fr:french-entry-with-default-value",
            "tags_xx": ["French entry with default value"],
            "tags_de": ["Special value for German 2"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "xx",
            "tags_ids_xx": ["language-less-entry"],
            "is_before": "fr:french-entry-with-default-value",
            "preceding_lines": [],
            "tags_ids_de": ["special-value-for-german-3"],
            "src_position": 119,
            "id": "xx:language-less-entry",
            "tags_xx": ["Language-less entry"],
            "tags_de": ["Special value for German 3"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "sv",
            "tags_sv": ["Ä-märket"],
            "tags_ids_xx": ["ä-märket"],
            "is_before": "xx:language-less-entry",
            "preceding_lines": ["# xx: entry with accents, need to match unaccented version"],
            "src_position": 123,
            "tags_ids_sv": ["ä-märket"],
            "id": "sv:ä-märket",
            "tags_xx": ["Ä-märket"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "main_language": "en",
            "tags_en": [
                "Entry with (parentheses) and some *!#{}@$ characters",
                "synonym with *%@$(]% chars",
            ],
            "is_before": "sv:ä-märket",
            "preceding_lines": [],
            "src_position": 126,
            "id": "en:entry-with-parentheses-and-some-characters",
            "tags_ids_en": ["entry-with-parentheses-and-some-characters", "synonym-with-chars"],
            "labels": {"ENTRY", "p_test_testbranch", "t_test", "b_testbranch"},
        },
        {
            "is_before": "en:entry-with-parentheses-and-some-characters",
            "preceding_lines": [],
            "src_position": 126,
            "id": "__footer__",
            "labels": {"p_test_testbranch", "t_test", "b_testbranch", "TEXT"},
        },
        {
            "warnings": ["parent not found for child fr:yaourts-myrtille with parent yaourt"],
            "branch_name": "testbranch",
            "created_at": "2023-11-16T00:36:22.663000000+00:00",
            "id": "p_test_testbranch",
            "taxonomy_name": "test",
            "errors": [],
            "labels": {"p_test_testbranch", "ERRORS", "t_test", "b_testbranch"},
        },
        {
            "branch_name": "testbranch",
            "description": "just a test branch",
            "created_at": "2023-11-16T00:36:22.686000000+00:00",
            "id": "p_test_testbranch",
            "taxonomy_name": "test",
            "status": "OPEN",
            "labels": {"PROJECT"},
        },
    ],
    "relations": [
        {"is_before": ["__header__", "stopwords:0"]},
        {"is_before": ["de:spätzle", "en:kale"]},
        {"is_before": ["en:banana-yogurts", "en:passion-fruit-yogurts"]},
        {"is_before": ["en:beef", "en:roast-beef"]},
        {"is_before": ["en:entry-with-parentheses-and-some-characters", "__footer__"]},
        {"is_before": ["en:fake-duck-meat", "en:vegetable"]},
        {"is_before": ["en:fake-meat", "en:fake-stuff"]},
        {"is_before": ["en:fake-stuff", "en:fake-duck-meat"]},
        {"is_before": ["en:fish-soup", "de:spätzle"]},
        {"is_before": ["en:kale", "en:kefir-2.5"]},
        {"is_before": ["en:kefir-2.5", "fr:french-entry"]},
        {"is_before": ["en:lemon-yogurts", "fr:yaourts-fruit-passion-alleges"]},
        {"is_before": ["en:meat", "en:beef"]},
        {"is_before": ["en:passion-fruit-yogurts", "fr:yaourts-alleges"]},
        {"is_before": ["en:roast-beef", "en:fake-meat"]},
        {"is_before": ["en:soup", "en:vegan-soup"]},
        {"is_before": ["en:vegan-soup", "en:fish-soup"]},
        {"is_before": ["en:vegetable", "en:soup"]},
        {"is_before": ["en:yogurts", "en:banana-yogurts"]},
        {"is_before": ["fr:french-entry", "fr:french-entry-with-default-value"]},
        {"is_before": ["fr:french-entry-with-default-value", "xx:language-less-entry"]},
        {"is_before": ["fr:yaourts-alleges", "en:lemon-yogurts"]},
        {"is_before": ["fr:yaourts-citron-alleges", "fr:yaourts-myrtille"]},
        {"is_before": ["fr:yaourts-fruit-passion-alleges", "fr:yaourts-citron-alleges"]},
        {"is_before": ["fr:yaourts-myrtille", "en:meat"]},
        {"is_before": ["stopwords:0", "synonyms:0"]},
        {"is_before": ["sv:ä-märket", "en:entry-with-parentheses-and-some-characters"]},
        {"is_before": ["synonyms:0", "synonyms:1"]},
        {"is_before": ["synonyms:1", "en:yogurts"]},
        {"is_before": ["xx:language-less-entry", "sv:ä-märket"]},
        {"is_child_of": ["en:banana-yogurts", "en:yogurts"]},
        {"is_child_of": ["en:beef", "en:meat"]},
        {"is_child_of": ["en:fake-duck-meat", "en:fake-meat"]},
        {"is_child_of": ["en:fake-duck-meat", "en:fake-stuff"]},
        {"is_child_of": ["en:fake-meat", "en:meat"]},
        {"is_child_of": ["en:fish-soup", "en:soup"]},
        {"is_child_of": ["en:lemon-yogurts", "en:yogurts"]},
        {"is_child_of": ["en:passion-fruit-yogurts", "en:yogurts"]},
        {"is_child_of": ["en:roast-beef", "en:beef"]},
        {"is_child_of": ["en:vegan-soup", "en:soup"]},
        {"is_child_of": ["fr:yaourts-alleges", "en:yogurts"]},
        {"is_child_of": ["fr:yaourts-citron-alleges", "en:lemon-yogurts"]},
        {"is_child_of": ["fr:yaourts-citron-alleges", "fr:yaourts-alleges"]},
        {"is_child_of": ["fr:yaourts-fruit-passion-alleges", "en:passion-fruit-yogurts"]},
        {"is_child_of": ["fr:yaourts-fruit-passion-alleges", "fr:yaourts-alleges"]},
    ],
}
