export const aa = [
  [
    {
      tags_ids_es: ["e100", "curcumina", "extracto-de-curcuma"],
      prop_vegetarian_en: "yes",
      tags_ids_et: ["e100", "kurkumiin"],
      tags_fr: ["E100", "curcumine", "extrait de curcuma"],
      tags_ids_mt: ["e100", "kurkumina"],
      tags_fi_str: "E100 kurkumiini kurkumiinia kurkumiiniuutetta",
      tags_ids_el: ["e100", "κουρκουμινη"],
      prop_additives_classes_en: " en:colour",
      tags_ids_en: ["e100", "curcumin", "turmeric-extract", "curcuma-extract"],
      tags_fi: ["E100", "kurkumiini", "kurkumiinia", "kurkumiiniuutetta"],
      tags_ids_uk: ["e100", "куркумін"],
      tags_ids_nl_be: ["e100", "curcumine"],
      tags_fa: ["E100", "کورکومین"],
      id: "en:e100",
      tags_he_str: "E100 כורכומין",
      tags_nl: ["E100", "curcumine", "kurkuma extract", "kurkuma-extract"],
      tags_pt_str: "E100 curcumina",
      tags_nb: ["E100", "kurkumin"],
      tags_vi: ["E100", "curcumin"],
      tags_nl_be: ["E100", "curcumine"],
      src_position: 50,
      tags_zh_str: "E100 姜黄素",
      tags_tr_str: "E100 kurkumin",
      tags_ids_lt: ["e100", "kurkuminas"],
      tags_es: ["E100", "curcumina", "extracto de cúrcuma"],
      tags_ids_lv: ["e100", "kurkumīns", "kurkuma-ekstrakts"],
      tags_et: ["E100", "kurkumiin"],
      tags_fr_str: "E100 curcumine extrait de curcuma",
      tags_ids_da: ["e100", "curcumin", "gurkemejeekstrakt"],
      tags_ids_tr: ["e100", "kurkumin"],
      tags_en: ["E100", "Curcumin", "Turmeric extract", "curcuma extract"],
      tags_ids_de: ["e100", "kurkumin", "kurkumaextrakt"],
      prop_efsa_evaluation_en:
        " Scientific Opinion on the re-evaluation of curcumin (E 100) as a food additive",
      tags_mt: ["E100", "kurkumina"],
      tags_el: ["E100", "κουρκουμινη"],
      tags_ids_th: ["e100", "เคอร์คูมิน"],
      tags_ids_ta: ["e100", "குர்க்குமின்"],
      tags_ids_cs: ["e100", "kurkumin"],
      tags_sv_str: "E100 kurkumin gurkmejaextrakt",
      preceding_lines: [
        "# azb:E100, کورکومین",
        "# en-ca:E100, curcumin",
        "# en-gb:E100, curcumin",
        "# sr-ec:E100, куркумин",
        "# sr-el:E100, kurkumin",
        "# yue:E100, 薑黃素",
        "# zh-cn:E100, 姜黄素",
        "# zh-hans:E100, 姜黄素",
        "# zh-hant:E100, 薑黃素",
        "# zh-hk:E100, 薑黃素",
        "# zh-mo:E100, 薑黃素",
        "# zh-sg:E100, 姜黄素",
        "# zh-my:E100, 姜黄素",
        "# zh-tw:E100, 薑黃素",
        "# fr:curcumin 80 products in 2 languages @2018-10-11",
      ],
      tags_ids_sv: ["e100", "kurkumin", "gurkmejaextrakt"],
      tags_ids_kn: ["e100", "ಕರ್ಕ್ಯುಮಿನ್"],
      tags_ids_ko: ["e100", "커큐민"],
      tags_hu: ["E100", "kurkumin"],
      tags_hr: ["E100", "kurkumin", "ekstrakt kurkume", "curcumin"],
      tags_ta_str: "E100 குர்க்குமின்",
      tags_hu_str: "E100 kurkumin",
      tags_pt: ["E100", "curcumina"],
      tags_sk_str: "E100 kurkumín",
      tags_it_str: "E100 curcumina estratto di curcuma",
      tags_ids_ca: ["e100", "curcumina"],
      tags_pl: ["E100", "kurkumina"],
      tags_nl_be_str: "E100 curcumine",
      tags_he: ["E100", "כורכומין"],
      tags_mt_str: "E100 kurkumina",
      tags_ids_sk: ["e100", "kurkumin"],
      tags_kn_str: "E100 ಕರ್ಕ್ಯುಮಿನ್",
      tags_ids_sl: ["e100", "kurkumin"],
      tags_ids_bs: ["e100", "kurkumin"],
      tags_ids_ru: ["e100", "куркумины"],
      tags_lv_str: "E100 kurkumīns kurkuma ekstrakts",
      tags_es_str: "E100 curcumina extracto de cúrcuma",
      tags_ids_bg: ["e100", "куркумин"],
      tags_vi_str: "E100 curcumin",
      tags_ids_ro: ["e100", "curcumină"],
      tags_ro_str: "E100 curcumină",
      tags_el_str: "E100 κουρκουμινη",
      tags_bs_str: "E100 kurkumin",
      tags_ga: ["E100", "curcumina"],
      tags_ids_ja: ["e100", "クルクミン"],
      tags_nl_str: "E100 curcumine kurkuma extract kurkuma-extract",
      tags_ids_it: ["e100", "curcumina", "estratto-di-curcuma"],
      tags_ids_zh: ["e100", "姜黄素"],
      tags_sk: ["E100", "kurkumín"],
      tags_sl: ["E100", "kurkumin"],
      tags_pl_str: "E100 kurkumina",
      tags_ids_ar: ["e100", "كركومين"],
      tags_ar_str: "E100 كركومين",
      prop_wikidata_en: "Q312266",
      tags_bs: ["E100", "kurkumin"],
      tags_lt_str: "E100 kurkuminas",
      tags_ids_id: ["e100", "kurkumin"],
      tags_bg: ["E100", "куркумин"],
      tags_ru: ["E100", "куркумины"],
      is_before: "synonyms:14",
      tags_ro: ["E100", "curcumină"],
      tags_id_str: "E100 kurkumin",
      tags_th_str: "E100 เคอร์คูมิน",
      tags_ru_str: "E100 куркумины",
      tags_uk_str: "E100 куркумін",
      tags_ids_hu: ["e100", "kurkumin"],
      prop_wikipedia_en: "https://en.wikipedia.org/wiki/Curcumin",
      tags_ja: ["E100", "クルクミン"],
      tags_en_str: "E100 Curcumin Turmeric extract curcuma extract",
      tags_ids_pt: ["e100", "curcumina"],
      tags_it: ["E100", "curcumina", "estratto di curcuma"],
      tags_de_str: "E100 Kurkumin Kurkumaextrakt",
      tags_ar: ["E100", "كركومين"],
      tags_zh: ["E100", "姜黄素"],
      tags_ids_hr: ["e100", "kurkumin", "ekstrakt-kurkume", "curcumin"],
      tags_ids_pl: ["e100", "kurkumina"],
      tags_ids_he: ["e100", "כורכומין"],
      main_language: "en",
      prop_vegan_en: "yes",
      tags_fa_str: "E100 کورکومین",
      tags_bg_str: "E100 куркумин",
      tags_id: ["E100", "kurkumin"],
      tags_ca_str: "E100 curcumina",
      tags_sl_str: "E100 kurkumin",
      tags_uk: ["E100", "куркумін"],
      tags_ko_str: "E100 커큐민",
      tags_lv: ["E100", "kurkumīns", "kurkuma ekstrakts"],
      tags_cs_str: "E100 kurkumin",
      tags_lt: ["E100", "kurkuminas"],
      tags_nb_str: "E100 kurkumin",
      tags_da: ["E100", "curcumin", "gurkemejeekstrakt"],
      tags_de: ["E100", "Kurkumin", "Kurkumaextrakt"],
      tags_tr: ["E100", "kurkumin"],
      tags_ids_ga: ["e100", "curcumina"],
      tags_th: ["E100", "เคอร์คูมิน"],
      tags_ids_fr: ["e100", "curcumine", "extrait-curcuma"],
      tags_hr_str: "E100 kurkumin ekstrakt kurkume curcumin",
      prop_efsa_evaluation_date_en: " 2010-09-06",
      tags_ids_fi: ["e100", "kurkumiini", "kurkumiinia", "kurkumiiniuutetta"],
      tags_da_str: "E100 curcumin gurkemejeekstrakt",
      tags_ta: ["E100", "குர்க்குமின்"],
      tags_ga_str: "E100 curcumina",
      prop_e_number_en: "100",
      tags_cs: ["E100", "kurkumin"],
      prop_efsa_evaluation_url_en:
        " http://dx.doi.org/10.2903/j.efsa.2010.1679",
      tags_ko: ["E100", "커큐민"],
      tags_ids_fa: ["e100", "کورکومین"],
      tags_sv: ["E100", "kurkumin", "gurkmejaextrakt"],
      tags_ids_nl: ["e100", "curcumine", "kurkuma-extract"],
      tags_kn: ["E100", "ಕರ್ಕ್ಯುಮಿನ್"],
      tags_ja_str: "E100 クルクミン",
      tags_ids_vi: ["e100", "curcumin"],
      tags_ids_nb: ["e100", "kurkumin"],
      tags_et_str: "E100 kurkumiin",
      tags_ca: ["E100", "curcumina"],
    },
  ],
  [
    {
      tags_ids_it: ["e106", "flavina-mononucleotide"],
      tags_ids_es: ["e106", "flavin-mononucleotido"],
      prop_vegetarian_en: "yes",
      tags_sk: ["E106", "E106 food additive"],
      tags_ids_et: ["e106", "e106-food-additive"],
      tags_sl: ["E106", "E106 food additive"],
      tags_pl_str: "E106 mononukleotyd flawinowy",
      tags_fr: ["E106", "Flavine mononucléotide"],
      prop_wikidata_en: "Q376061",
      tags_ids_mt: ["e106", "e106-food-additive"],
      tags_fi_str: "E106 E106 food additive",
      tags_ids_el: ["e106", "e106-food-additive"],
      tags_ids_en: ["e106", "flavin-mononucleotide"],
      tags_lt_str: "E106 E106 food additive",
      tags_bg: ["E106", "E106 food additive"],
      tags_fi: ["E106", "E106 food additive"],
      is_before: "en:e100",
      tags_ro: ["E106", "E106 food additive"],
      id: "en:e106",
      tags_nl: ["E106", "E106 food additive"],
      tags_pt_str: "E106 Mononucleótido de flavina",
      tags_ids_hu: ["e106", "flavin-mononukleotid"],
      src_position: 120,
      tags_en_str: "E106 flavin mononucleotide",
      tags_ids_pt: ["e106", "mononucleotido-de-flavina"],
      tags_it: ["E106", "Flavina mononucleotide"],
      tags_de_str: "E106 Flavinmononukleotid",
      tags_ids_lt: ["e106", "e106-food-additive"],
      tags_es: ["E106", "Flavín mononucleótido"],
      tags_ids_lv: ["e106", "e106-food-additive"],
      tags_et: ["E106", "E106 food additive"],
      tags_ids_pl: ["e106", "mononukleotyd-flawinowy"],
      tags_fr_str: "E106 Flavine mononucléotide",
      tags_ids_da: ["e106", "e106-food-additive"],
      main_language: "en",
      prop_vegan_en: "yes",
      tags_en: ["E106", "flavin mononucleotide"],
      tags_ids_de: ["e106", "flavinmononukleotid"],
      tags_mt: ["E106", "E106 food additive"],
      tags_el: ["E106", "E106 food additive"],
      tags_bg_str: "E106 E106 food additive",
      tags_sl_str: "E106 E106 food additive",
      tags_ids_cs: ["e106", "flavinmononukleotid"],
      tags_sv_str: "E106 FMN",
      preceding_lines: [
        "",
        "# WARNING:e106 is the same as e101a, moved synonyms to E101a",
        "",
        "# comment:en:used to be extracted from milk, but not anymore.",
      ],
      tags_ids_sv: ["e106", "fmn"],
      tags_hu: ["E106", "flavin-mononukleotid"],
      tags_lv: ["E106", "E106 food additive"],
      tags_cs_str: "E106 flavinmononukleotid",
      tags_hu_str: "E106 flavin-mononukleotid",
      tags_pt: ["E106", "Mononucleótido de flavina"],
      tags_sk_str: "E106 E106 food additive",
      tags_it_str: "E106 Flavina mononucleotide",
      tags_lt: ["E106", "E106 food additive"],
      tags_pl: ["E106", "mononukleotyd flawinowy"],
      tags_da: ["E106", "E106 food additive"],
      tags_mt_str: "E106 E106 food additive",
      tags_ids_sk: ["e106", "e106-food-additive"],
      tags_de: ["E106", "Flavinmononukleotid"],
      tags_ids_sl: ["e106", "e106-food-additive"],
      tags_ids_fr: ["e106", "flavine-mononucleotide"],
      tags_ids_fi: ["e106", "e106-food-additive"],
      tags_da_str: "E106 E106 food additive",
      tags_lv_str: "E106 E106 food additive",
      tags_es_str: "E106 Flavín mononucleótido",
      tags_ids_bg: ["e106", "e106-food-additive"],
      prop_e_number_en: "106",
      tags_cs: ["E106", "flavinmononukleotid"],
      tags_ids_ro: ["e106", "e106-food-additive"],
      tags_sv: ["E106", "FMN"],
      tags_ro_str: "E106 E106 food additive",
      tags_ids_nl: ["e106", "e106-food-additive"],
      tags_el_str: "E106 E106 food additive",
      tags_et_str: "E106 E106 food additive",
      tags_nl_str: "E106 E106 food additive",
    },
  ],
  [
    {
      tags_ids_it: [
        "e101",
        "riboflavina",
        "vitamina-g",
        "vitamina-b2",
        "c17h20n4o6",
      ],
      tags_ids_es: ["e101", "riboflavina", "vitamina-b2", "lactoflavina"],
      prop_vegetarian_en: "yes",
      tags_sk: [
        "E101",
        "Riboflavín",
        "Vitamín G",
        "Ovoflavín",
        "Vitamín B2",
        "Laktoflavín",
      ],
      tags_ids_et: [
        "e101",
        "vitamiin-b2",
        "b2-vitamiin",
        "laktoflaviin",
        "riboflaviin",
      ],
      tags_sl: ["E101", "Riboflavin", "Vitamin B2"],
      tags_pl_str: "E101 Witamina B2 Witamina G Ryboflawina Laktoflawina",
      tags_fr: ["E101", "Riboflavine", "vitamine B2", "Bacillus subtilis"],
      prop_wikidata_en: "Q130365",
      tags_ids_mt: ["e101", "e101-food-additive"],
      tags_fi_str:
        "E101 Riboflaviini B2-vitamiini Laktoflaviini Riboflaviinia B2-vitamiinia Laktoflaviinia",
      tags_ids_el: ["e101", "e101-food-additive"],
      prop_additives_classes_en: " en:colour",
      tags_ids_en: [
        "e101",
        "riboflavin",
        "vitamin-b2",
        "flavaxin",
        "vitamin-b-2",
        "vitamin-g",
        "riboflavine",
        "lactoflavine",
        "lactoflavin",
      ],
      tags_lt_str: "E101 Riboflavinas Vitaminas G",
      tags_bg: ["E101", "E101 food additive"],
      tags_fi: [
        "E101",
        "Riboflaviini",
        "B2-vitamiini",
        "Laktoflaviini",
        "Riboflaviinia",
        "B2-vitamiinia",
        "Laktoflaviinia",
      ],
      is_before: "en:e106",
      tags_ro: ["E101", "Riboflavină", "Vitamina B2"],
      tags_ids_nl_be: ["e101", "riboflavine", "vitamine-b2", "lactoflavine"],
      id: "en:e101",
      tags_nl: ["E101", "Riboflavine", "Vitamine B2", "Lactoflavine"],
      tags_pt_str: "E101 Riboflavina Vitamina b2 Vitamina G",
      tags_ids_hu: ["e101", "riboflavin", "laktoflavin", "b2-vitamin"],
      tags_nl_be: ["E101", "Riboflavine", "Vitamine B2", "Lactoflavine"],
      src_position: 148,
      tags_en_str:
        "E101 Riboflavin Vitamin B2 Flavaxin Vitamin B 2 Vitamin G Riboflavine Lactoflavine Lactoflavin",
      tags_ids_pt: ["e101", "riboflavina", "vitamina-b2", "vitamina-g"],
      tags_it: [
        "E101",
        "Riboflavina",
        "Vitamina G",
        "Vitamina B2",
        "C17H20N4O6",
      ],
      tags_tr_str:
        "E101 Riboflavin B2 Vitamini B2 Vitamin Vitamin B2 Laktoflavin",
      tags_de_str:
        "E101 Riboflavin Vitamin B2 Vitamin G Lactoflavin Laktoflavin",
      tags_ids_lt: ["e101", "riboflavinas", "vitaminas-g"],
      tags_es: ["E101", "Riboflavina", "Vitamina B2", "Lactoflavina"],
      tags_ids_lv: ["e101", "b2-vitamīns", "riboflavīns"],
      tags_ids_hr: ["e101", "riboflavini", "riboflavin"],
      tags_et: [
        "E101",
        "Vitamiin B2",
        "B2-vitamiin",
        "Laktoflaviin",
        "Riboflaviin",
      ],
      tags_ids_pl: [
        "e101",
        "witamina-b2",
        "witamina-g",
        "ryboflawina",
        "laktoflawina",
      ],
      tags_fr_str: "E101 Riboflavine vitamine B2 Bacillus subtilis",
      tags_ids_da: ["e101", "e101-food-additive"],
      tags_ids_tr: [
        "e101",
        "riboflavin",
        "b2-vitamini",
        "b2-vitamin",
        "vitamin-b2",
        "laktoflavin",
      ],
      main_language: "en",
      prop_vegan_en: "maybe",
      tags_en: [
        "E101",
        "Riboflavin",
        "Vitamin B2",
        "Flavaxin",
        "Vitamin B 2",
        "Vitamin G",
        "Riboflavine",
        "Lactoflavine",
        "Lactoflavin",
      ],
      tags_ids_de: [
        "e101",
        "riboflavin",
        "vitamin-b2",
        "vitamin-g",
        "lactoflavin",
        "laktoflavin",
      ],
      prop_efsa_evaluation_en:
        " Scientific Opinion on the re-evaluation of riboflavin (E 101i) and riboflavin-5'-phosphate sodium (E 101ii) as food additives.",
      tags_mt: ["E101", "E101 food additive"],
      tags_el: ["E101", "E101 food additive"],
      tags_bg_str: "E101 E101 food additive",
      tags_ca_str: "E101 Riboflavina",
      tags_sl_str: "E101 Riboflavin Vitamin B2",
      tags_ids_cs: [
        "e101",
        "riboflavin",
        "ovoflavin",
        "vitamin-b-2",
        "vitamin-b2",
        "laktoflavin",
        "vitamín-g",
        "lactoflavin",
      ],
      tags_sv_str: "E101 Riboflavin Vitamin B2 B2-vitamin",
      preceding_lines: [],
      tags_ids_sv: ["e101", "riboflavin", "vitamin-b2", "b2-vitamin"],
      tags_hu: ["E101", "Riboflavin", "Laktoflavin", "B2-vitamin"],
      tags_lv: ["E101", "B2 vitamīns", "Riboflavīns"],
      tags_hr: ["E101", "riboflavini", "riboflavin"],
      tags_cs_str:
        "E101 Riboflavin Ovoflavin Vitamin B 2 Vitamin B2 Laktoflavin Vitamín G Lactoflavin",
      tags_hu_str: "E101 Riboflavin Laktoflavin B2-vitamin",
      tags_pt: ["E101", "Riboflavina", "Vitamina b2", "Vitamina G"],
      tags_sk_str: "E101 Riboflavín Vitamín G Ovoflavín Vitamín B2 Laktoflavín",
      tags_it_str: "E101 Riboflavina Vitamina G Vitamina B2 C17H20N4O6",
      tags_ids_ca: ["e101", "riboflavina"],
      tags_lt: ["E101", "Riboflavinas", "Vitaminas G"],
      tags_pl: [
        "E101",
        "Witamina B2",
        "Witamina G",
        "Ryboflawina",
        "Laktoflawina",
      ],
      tags_nl_be_str: "E101 Riboflavine Vitamine B2 Lactoflavine",
      tags_da: ["E101", "E101 food additive"],
      tags_mt_str: "E101 E101 food additive",
      tags_ids_sk: [
        "e101",
        "riboflavin",
        "vitamin-g",
        "ovoflavin",
        "vitamin-b2",
        "laktoflavin",
      ],
      tags_de: [
        "E101",
        "Riboflavin",
        "Vitamin B2",
        "Vitamin G",
        "Lactoflavin",
        "Laktoflavin",
      ],
      tags_tr: [
        "E101",
        "Riboflavin",
        "B2 Vitamini",
        "B2 Vitamin",
        "Vitamin B2",
        "Laktoflavin",
      ],
      tags_ids_sl: ["e101", "riboflavin", "vitamin-b2"],
      tags_ids_fr: ["e101", "riboflavine", "vitamine-b2", "bacillus-subtilis"],
      tags_hr_str: "E101 riboflavini riboflavin",
      prop_efsa_evaluation_date_en: " 2013-10-22",
      tags_ids_fi: [
        "e101",
        "riboflaviini",
        "b2-vitamiini",
        "laktoflaviini",
        "riboflaviinia",
        "b2-vitamiinia",
        "laktoflaviinia",
      ],
      tags_da_str: "E101 E101 food additive",
      tags_lv_str: "E101 B2 vitamīns Riboflavīns",
      tags_es_str: "E101 Riboflavina Vitamina B2 Lactoflavina",
      tags_ids_bg: ["e101", "e101-food-additive"],
      prop_e_number_en: "101",
      tags_cs: [
        "E101",
        "Riboflavin",
        "Ovoflavin",
        "Vitamin B 2",
        "Vitamin B2",
        "Laktoflavin",
        "Vitamín G",
        "Lactoflavin",
      ],
      prop_efsa_evaluation_url_en:
        " http://dx.doi.org/10.2903/j.efsa.2013.3357",
      tags_ids_ro: ["e101", "riboflavină", "vitamina-b2"],
      tags_sv: ["E101", "Riboflavin", "Vitamin B2", "B2-vitamin"],
      tags_ro_str: "E101 Riboflavină Vitamina B2",
      tags_ids_nl: ["e101", "riboflavine", "vitamine-b2", "lactoflavine"],
      tags_el_str: "E101 E101 food additive",
      tags_et_str: "E101 Vitamiin B2 B2-vitamiin Laktoflaviin Riboflaviin",
      tags_nl_str: "E101 Riboflavine Vitamine B2 Lactoflavine",
      tags_ca: ["E101", "Riboflavina"],
    },
  ],
  [
    {
      tags_ids_it: ["e101a", "e101a-food-additive"],
      tags_ids_es: ["e101a", "e101a-food-additive"],
      tags_sk: ["E101a", "E101a food additive"],
      tags_ids_et: ["e101a", "e101a-food-additive"],
      tags_sl: ["E101a", "E101a food additive"],
      tags_pl_str: "E101a E101a food additive",
      tags_fr: [
        "E101a",
        "5'-phosphate sodique de riboflavine",
        "phosphate-5' de riboflavine de sodium",
        "sel monosodique de l'ester du phosphate-5' de riboflavine",
        "sel monosodique de l'ester de phosphate de la vitamine B2",
        "sel de l'ester monosodique de la riboflavine 5-monophosphatée",
      ],
      prop_wikidata_en: "Q130365",
      tags_ids_mt: ["e101a", "e101a-food-additive"],
      tags_fi_str: "E101a Flaviinimononukleotidi Flaviinimononukleotidia FMN",
      tags_ids_el: ["e101a", "e101a-food-additive"],
      prop_additives_classes_en: " en:colour",
      tags_ids_en: ["e101a", "e101a-food-additive"],
      tags_lt_str: "E101a E101a food additive",
      tags_bg: ["E101a", "E101a food additive"],
      tags_fi: [
        "E101a",
        "Flaviinimononukleotidi",
        "Flaviinimononukleotidia",
        "FMN",
      ],
      is_before: "en:e101ii",
      tags_ro: ["E101a", "E101a food additive"],
      id: "en:e101a",
      tags_nl: ["E101a", "E101a food additive"],
      tags_pt_str: "E101a E101a food additive",
      tags_ids_hu: ["e101a", "e101a-food-additive"],
      prop_comment_en:
        "E101a is the same as E101ii. All synonyms are under E101ii. Needs more cleanup",
      src_position: 249,
      tags_en_str: "E101a E101a food additive",
      tags_ids_pt: ["e101a", "e101a-food-additive"],
      tags_it: ["E101a", "E101a food additive"],
      tags_de_str: "E101a E101a food additive",
      tags_ids_lt: ["e101a", "e101a-food-additive"],
      tags_es: ["E101a", "E101a food additive"],
      tags_ids_lv: ["e101a", "e101a-food-additive"],
      tags_ids_hr: ["e101a", "natrijev-riboflavin-5-fosfat"],
      tags_et: ["E101a", "E101a food additive"],
      tags_ids_pl: ["e101a", "e101a-food-additive"],
      tags_fr_str:
        "E101a 5'-phosphate sodique de riboflavine phosphate-5' de riboflavine de sodium sel monosodique de l'ester du phosphate-5' de riboflavine sel monosodique de l'ester de phosphate de la vitamine B2 sel de l'ester monosodique de la riboflavine 5-monophosphatée",
      tags_ids_da: ["e101a", "e101a-food-additive"],
      main_language: "en",
      tags_en: ["E101a", "E101a food additive"],
      tags_ids_de: ["e101a", "e101a-food-additive"],
      prop_efsa_evaluation_en:
        " Scientific Opinion on the re-evaluation of riboflavin (E 101i) and riboflavin-5'-phosphate sodium (E 101ii) as food additives.",
      tags_mt: ["E101a", "E101a food additive"],
      tags_el: ["E101a", "E101a food additive"],
      tags_bg_str: "E101a E101a food additive",
      tags_sl_str: "E101a E101a food additive",
      tags_ids_cs: ["e101a", "e101a-food-additive"],
      tags_sv_str: "E101a E101a food additive",
      preceding_lines: [],
      tags_ids_sv: ["e101a", "e101a-food-additive"],
      tags_hu: ["E101a", "E101a food additive"],
      tags_lv: ["E101a", "E101a food additive"],
      tags_hr: ["E101a", "natrijev riboflavin 5-fosfat"],
      tags_cs_str: "E101a E101a food additive",
      tags_hu_str: "E101a E101a food additive",
      tags_pt: ["E101a", "E101a food additive"],
      tags_sk_str: "E101a E101a food additive",
      tags_it_str: "E101a E101a food additive",
      tags_lt: ["E101a", "E101a food additive"],
      tags_pl: ["E101a", "E101a food additive"],
      tags_da: ["E101a", "E101a food additive"],
      tags_mt_str: "E101a E101a food additive",
      tags_ids_sk: ["e101a", "e101a-food-additive"],
      tags_de: ["E101a", "E101a food additive"],
      tags_ids_sl: ["e101a", "e101a-food-additive"],
      tags_ids_fr: [
        "e101a",
        "5-phosphate-sodique-riboflavine",
        "phosphate-5-riboflavine-sodium",
        "sel-monosodique-l-ester-phosphate-5-riboflavine",
        "sel-monosodique-l-ester-phosphate-vitamine-b2",
        "sel-l-ester-monosodique-riboflavine-5-monophosphatee",
      ],
      tags_hr_str: "E101a natrijev riboflavin 5-fosfat",
      prop_efsa_evaluation_date_en: " 2013-10-22",
      tags_ids_fi: [
        "e101a",
        "flaviinimononukleotidi",
        "flaviinimononukleotidia",
        "fmn",
      ],
      tags_da_str: "E101a E101a food additive",
      tags_lv_str: "E101a E101a food additive",
      tags_es_str: "E101a E101a food additive",
      tags_ids_bg: ["e101a", "e101a-food-additive"],
      prop_e_number_en: "101a",
      tags_cs: ["E101a", "E101a food additive"],
      prop_efsa_evaluation_url_en:
        " http://dx.doi.org/10.2903/j.efsa.2013.3357",
      tags_ids_ro: ["e101a", "e101a-food-additive"],
      tags_sv: ["E101a", "E101a food additive"],
      tags_ro_str: "E101a E101a food additive",
      tags_ids_nl: ["e101a", "e101a-food-additive"],
      tags_el_str: "E101a E101a food additive",
      tags_et_str: "E101a E101a food additive",
      tags_nl_str: "E101a E101a food additive",
    },
  ],
  [
    {
      tags_ids_es: [
        "e102",
        "tartrazina",
        "tartracina",
        "yellow-5",
        "amarillo-5",
        "e-102",
        "amarillo-ocaso-fcf",
        "amarillo-fd-c-5",
      ],
      prop_vegetarian_en: "yes",
      tags_ids_et: ["e102", "tartrasiin", "e-102"],
      tags_fr: [
        "E102",
        "Tartrazine",
        "FD&C Yellow 5",
        "FD&C Jaune 5",
        "Yellow 5",
        "FD&C Yellow #5",
        "C.I. Food Yellow 4",
        "C.I. Acid Yellow 23",
        "Acid Yellow 23",
        "C.I. 19140",
        "Yellow number 5",
        "E-102",
        "1934-21-0",
      ],
      tags_ids_mt: ["e102", "tartrażina"],
      tags_fi_str: "E102 Tartratsiini Tartratsiinia CI 19140 E 102",
      tags_ids_el: ["e102", "ταρτραζινη"],
      prop_additives_classes_en: " en:colour",
      tags_ids_en: [
        "e102",
        "tartrazine",
        "yellow-5",
        "yellow-number-5",
        "yellow-no-5",
        "yellow-no5",
        "fd-c-yellow-5",
        "fd-c-yellow-no-5",
        "fd-c-yellow-no5",
        "fd-and-c-yellow-no.-5",
        "fd-and-c-yellow-5",
        "yellow-5-lake",
      ],
      prop_efsa_en: "http://www.efsa.europa.eu/fr/efsajournal/doc/1331.pdf",
      tags_fi: ["E102", "Tartratsiini", "Tartratsiinia", "CI 19140", "E 102"],
      tags_ids_uk: ["e102", "тартразин"],
      tags_ids_nl_be: ["e102", "tartrazine"],
      tags_fa: ["E102", "تارترازین"],
      id: "en:e102",
      tags_he_str: "E102 טרטרזין",
      tags_nl: ["E102", "Tartrazine"],
      tags_pt_str:
        "E102 Tartarazina Tartrazina Corante amarelo tartrazina Amarelo tartrazina",
      tags_nb: ["E102", "Tartrazin"],
      tags_nl_be: ["E102", "Tartrazine"],
      src_position: 281,
      tags_zh_str: "E102 :柠檬黄",
      tags_tr_str: "E102 Tartrazin",
      tags_ids_lt: ["e102", "tartrazinas"],
      tags_es: [
        "E102",
        "Tartrazina",
        "Tartracina",
        "Yellow 5",
        "Amarillo 5",
        "E-102",
        "amarillo ocaso FCF",
        "amarillo FD&C 5",
      ],
      tags_ids_lv: ["e102", "tartrazīns"],
      tags_et: ["E102", "Tartrasiin", "E 102"],
      tags_fr_str:
        "E102 Tartrazine FD&C Yellow 5 FD&C Jaune 5 Yellow 5 FD&C Yellow #5 C.I. Food Yellow 4 C.I. Acid Yellow 23 Acid Yellow 23 C.I. 19140 Yellow number 5 E-102 1934-21-0",
      tags_ids_da: ["e102", "tartrazin", "e-102"],
      tags_ids_tr: ["e102", "tartrazin"],
      tags_en: [
        "E102",
        "Tartrazine",
        "Yellow 5",
        "Yellow number 5",
        "Yellow no 5",
        "Yellow no5",
        "FD&C Yellow 5",
        "FD&C Yellow no 5",
        "FD&C Yellow no5",
        "FD and C Yellow no. 5",
        "FD and C Yellow 5",
        "Yellow 5 lake",
      ],
      tags_ids_de: ["e102", "tartrazin", "yellow-5", "e-102"],
      prop_efsa_evaluation_en:
        " Scientific Opinion on the re-evaluation Tartrazine (E 102)",
      tags_mt: ["E102", "Tartrażina"],
      tags_el: ["E102", "Ταρτραζινη"],
      prop_description_en:
        "TARTRAZINE is a synthetic lemon yellow azo dye primarily used as a food coloring.",
      tags_ids_cs: ["e102", "tartrazin", "fd-c-žluť-5", "e-102", "tartazin"],
      tags_sv_str: "E102 Tartrazin E 102 Tartrasin",
      preceding_lines: [
        "",
        "# azb:E102, تارترازین",
        "# zh-cn:E102, 柠檬黄",
        "# zh-hans:E102, 柠檬黄",
        "# zh-hant:E102, 檸檬黃",
        "# zh-hk:E102, 檸檬黃",
        "# zh-sg:E102, 柠檬黄",
        "# zh-tw:E102, 檸檬黃",
        "# ingredient/fr:tartrazine has 196 products in 3 languages @2019-02-09",
      ],
      tags_ids_sv: ["e102", "tartrazin", "e-102", "tartrasin"],
      tags_ids_ko: ["e102", "타트라진"],
      tags_hu: ["E102", "Tartrazin"],
      tags_hr: ["E102", "Tartrazin"],
      tags_hu_str: "E102 Tartrazin",
      tags_pt: [
        "E102",
        "Tartarazina",
        "Tartrazina",
        "Corante amarelo tartrazina",
        "Amarelo tartrazina",
      ],
      tags_sk_str: "E102 Tartrazín",
      tags_it_str: "E102 Tartrazina",
      tags_ids_ca: ["e102", "tartrazina"],
      tags_ids_sr: ["tartrazin"],
      tags_pl: ["E102", "Tartrazyna"],
      tags_nl_be_str: "E102 Tartrazine",
      tags_he: ["E102", "טרטרזין"],
      tags_ids_sh: ["e102", "tartrazin"],
      tags_ids_si: ["e102", "ටාට්‍රසින්"],
      tags_mt_str: "E102 Tartrażina",
      tags_ids_sk: ["e102", "tartrazin"],
      tags_ids_sl: ["e102", "tartrazin"],
      tags_si_str: "E102 ටාට්‍රසින්",
      tags_ids_ru: ["e102", "тартразин", "е102", "tartrazine"],
      tags_lv_str: "E102 Tartrazīns",
      tags_es_str:
        "E102 Tartrazina Tartracina Yellow 5 Amarillo 5 E-102 amarillo ocaso FCF amarillo FD&C 5",
      tags_ids_bg: ["e102", "тартразин"],
      prop_colour_index_en: "CI 19140",
      tags_gl: ["E102", "Tartrazina"],
      tags_sr_str: "Tartrazin",
      tags_ids_ro: ["e102", "tartrazină"],
      tags_ro_str: "E102 Tartrazină",
      tags_el_str: "E102 Ταρτραζινη",
      tags_ga: ["E102", "Tartraiséin"],
      tags_ids_ja: ["e102", "タートラジン"],
      tags_nl_str: "E102 Tartrazine",
      tags_ids_it: ["e102", "tartrazina"],
      tags_sh: ["E102", "Tartrazin"],
      tags_ids_zh: ["e102", "柠檬黄"],
      tags_sk: ["E102", "Tartrazín"],
      tags_sl: ["E102", "Tartrazin"],
      tags_si: ["E102", "ටාට්‍රසින්"],
      tags_pl_str: "E102 Tartrazyna",
      prop_wikidata_en: "Q407158",
      tags_lt_str: "E102 Tartrazinas",
      tags_ids_id: ["e102", "tartrazina"],
      tags_bg: ["E102", "Тартразин"],
      tags_ru: ["E102", "Тартразин", "Е102", "Tartrazine"],
      tags_sh_str: "E102 Tartrazin",
      is_before: "en:e101a",
      tags_ro: ["E102", "Tartrazină"],
      tags_id_str: "E102 Tartrazina",
      tags_ru_str: "E102 Тартразин Е102 Tartrazine",
      tags_uk_str: "E102 Тартразин",
      tags_ids_hu: ["e102", "tartrazin"],
      prop_wikipedia_en: "https://en.wikipedia.org/wiki/Tartrazine",
      tags_ja: ["E102", ":タートラジン"],
      tags_en_str:
        "E102 Tartrazine Yellow 5 Yellow number 5 Yellow no 5 Yellow no5 FD&C Yellow 5 FD&C Yellow no 5 FD&C Yellow no5 FD and C Yellow no. 5 FD and C Yellow 5 Yellow 5 lake",
      tags_ids_pt: [
        "e102",
        "tartarazina",
        "tartrazina",
        "corante-amarelo-tartrazina",
        "amarelo-tartrazina",
      ],
      tags_it: ["E102", "Tartrazina"],
      tags_de_str: "E102 Tartrazin Yellow 5 E 102",
      tags_zh: ["E102", ":柠檬黄"],
      tags_ids_hr: ["e102", "tartrazin"],
      tags_ids_pl: ["e102", "tartrazyna"],
      tags_ids_he: ["e102", "טרטרזין"],
      main_language: "en",
      prop_vegan_en: "yes",
      tags_fa_str: "E102 تارترازین",
      tags_bg_str: "E102 Тартразин",
      tags_id: ["E102", "Tartrazina"],
      tags_ca_str: "E102 Tartrazina",
      tags_sl_str: "E102 Tartrazin",
      tags_uk: ["E102", "Тартразин"],
      tags_ko_str: "E102 타트라진",
      tags_ids_gl: ["e102", "tartrazina"],
      tags_lv: ["E102", "Tartrazīns"],
      tags_gl_str: "E102 Tartrazina",
      tags_cs_str: "E102 Tartrazin FD&C žluť 5 E 102 Tartazin",
      tags_lt: ["E102", "Tartrazinas"],
      tags_nb_str: "E102 Tartrazin",
      tags_da: ["E102", "Tartrazin", "E-102"],
      tags_de: ["E102", "Tartrazin", "Yellow 5", "E 102"],
      tags_tr: ["E102", "Tartrazin"],
      tags_ids_ga: ["e102", "tartraiséin"],
      tags_ids_fr: [
        "e102",
        "tartrazine",
        "fd-c-yellow-5",
        "fd-c-jaune-5",
        "yellow-5",
        "c.i.-food-yellow-4",
        "c.i.-acid-yellow-23",
        "acid-yellow-23",
        "c.i.-19140",
        "yellow-number-5",
        "e-102",
        "1934-21-0",
      ],
      tags_hr_str: "E102 Tartrazin",
      prop_efsa_evaluation_date_en: " 2009-11-12",
      tags_ids_fi: [
        "e102",
        "tartratsiini",
        "tartratsiinia",
        "ci-19140",
        "e-102",
      ],
      tags_da_str: "E102 Tartrazin E-102",
      tags_ga_str: "E102 Tartraiséin",
      prop_e_number_en: "102",
      tags_cs: ["E102", "Tartrazin", "FD&C žluť 5", "E 102", "Tartazin"],
      prop_efsa_evaluation_url_en:
        " http://dx.doi.org/10.2903/j.efsa.2009.1331",
      tags_ko: ["E102", "타트라진"],
      tags_ids_fa: ["e102", "تارترازین"],
      tags_sv: ["E102", "Tartrazin", "E 102", "Tartrasin"],
      tags_ids_nl: ["e102", "tartrazine"],
      tags_ja_str: "E102 :タートラジン",
      tags_ids_nb: ["e102", "tartrazin"],
      tags_et_str: "E102 Tartrasiin E 102",
      tags_ca: ["E102", "Tartrazina"],
      tags_sr: ["Tartrazin"],
    },
  ],
];
