name: taxonomy-editor code quality checks and unit tests

on:
  pull_request:

jobs:
  # taxonomy editor quality for frontend and backend
  taxonomy-editor-checks:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Make checks
        run: |
          export USER_UID=$(id -u)
          export USER_GID=$(id -g)
          make checks
